apiVersion: skaffold/v2beta11
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.VER}}"
  artifacts:    
    - image: board-api
      jib:
        args:
          - -DskipTests

profiles:  
  - name: kind
    build:
      local:
        push: false
      artifacts:
        - image: board-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind" 
    deploy:
      kubectl:
        manifests:
          - k8s/kind/*.yaml
          

  - name: kind-push
    build:
      local:
        push: true
      artifacts:
        - image: jacksonkim/board-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"

  