apiVersion: skaffold/v2beta11
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.VER}}"
  artifacts:    
    - image: board-api
      jib:
        args:
          - -DskipTests

profiles:  
  - name: hub
    build:
      local:
        push: true
      artifacts:
        - image: jacksonkim/board-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      kubectl:
        manifests:
          - k8s/cloud/board-api-deploy-hub.yaml
          - k8s/cloud/board-api-svc.yaml
          - k8s/cloud/mysql-deployment.yaml

  - name: hub-private
    build:
      local:
        push: true
      artifacts:
        - image: jacksonkim/private
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      kubectl:
        manifests:
          - k8s/cloud/board-api-deploy-hub-private.yaml
          - k8s/cloud/board-api-svc.yaml
          - k8s/cloud/mysql-deployment.yaml

  - name: ecr
    build:
      local:
        push: true
      artifacts:
        - image: 723184425190.dkr.ecr.ap-northeast-2.amazonaws.com/board-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      kubectl:
        manifests:
          - k8s/cloud/board-api-deploy-ecr.yaml
          - k8s/cloud/board-api-svc.yaml
          - k8s/cloud/mysql-deployment.yaml

  - name: gcr
    build:
      local:
        push: true
      artifacts:
        - image: gcr.io/durable-will-304110/board-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      kubectl:
        manifests:
          - k8s/cloud/board-api-deploy-gcr.yaml
          - k8s/cloud/board-api-svc.yaml
        #  - k8s/cloud/mysql-deployment.yaml

  