apiVersion: apps/v1

kind: Deployment

metadata:
  name: board-api
  namespace: api
  labels:
    env: dev

spec:
  #replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev

    spec:
      containers:
        - name: board-api
          image: 723184425190.dkr.ecr.ap-northeast-2.amazonaws.com/board-api
          ports:
          - containerPort: 8080
