apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: db
spec:
  type: LoadBalancer
  #type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    #targetPort: 3306
  selector:
    app: mysql
#spec:
#  ports:
#  - port: 3306
#  selector:
#    app: mysql
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: db
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        ## emptyDir
        emptyDir: {}
        ## hostPath
        #hostPath:
          #path: /tmp
          #type: Directory
        ## pvc  
        #persistentVolumeClaim:
        #  claimName: mysql-pv-claim

