apiVersion: v1
kind: Service

metadata:
  name: board-api-svc
  namespace: api
spec:
  selector:
    app: board-api
  
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: http
   # nodePort: 32180
  #type: NodePort
  